export const elements = {
  addContactButton: document.querySelector("#btn-add-contact"),
  formSection: document.querySelector("#contact-form-section"),
  form: document.querySelector("#contact-form"),
  formTitle: document.querySelector("#form-title"),
  formError: document.querySelector("#form-error"),
  cancelButton: document.querySelector("#btn-cancel-contact"),
  saveButton: document.querySelector("#btn-save-contact"),
  nameInput: document.querySelector("#contact-name"),
  emailInput: document.querySelector("#contact-email"),
  groupSelect: document.querySelector("#contact-group"),
  favoriteInput: document.querySelector("#contact-favorite"),
  addPhoneButton: document.querySelector("#btn-add-phone"),
  phonesContainer: document.querySelector("#phones-container"),
  addAddressButton: document.querySelector("#btn-add-address"),
  addressesContainer: document.querySelector("#addresses-container"),
  searchInput: document.querySelector("#search-input"),
  tableBody: document.querySelector("#table-address-book tbody"),
  emptyState: document.querySelector("#empty-state"),
  contactCount: document.querySelector("#contact-count"),
  groupForm: document.querySelector("#group-form"),
  groupNameInput: document.querySelector("#group-name"),
  groupList: document.querySelector("#group-list"),
  groupCount: document.querySelector("#group-count"),
  groupSidebar: document.querySelector("#group-sidebar"),
};
